github:
  full_name: "Fernando Levin"
  email: "flevin58@gmail.com"
#
# Used by the zshenv template and by tasks adding variables
# New entries will be added before env_end / path_end
# or after env_start / path_start
#
zshenv:
  path_start: "#-- PATH starting point"
  path_end: "#-- PATH ending point"
  env_start: "#-- ENV vars starting point"
  env_end: "#-- ENV vars ending point"
#
# Define the list of core tools to install
# Used by task core_tools.yml
#
core_tools:
  - curl
  - fastfetch
  - fzf
  - gum
  - just
  - luarocks
  - nodejs
  - ripgrep
  - wget
#
# Define which programming languages to install
# Note: lua is installed by default
# Includes VS Code extensions
#
projects_dir: "$HOME/Projects"
install_cpp: true
install_go: true
install_rust: true
install_zig: true
install_c3: false
#
# Define the list of developer tools to install
# These include formatters, lsp, linters etc.
# Used by task dev_tools.yml and by nvim
#
develop_tools:
  - prettier
  - prettierd
  - lua-language-server
  - stylua
  - shfmt
  - tombi
  - yamlfmt
  - jq
#
# Nerd fonts page: https://www.nerdfonts.com/font-downloads
# Caution: the name of the active_font will be used in wezterm, ptyxis, vscode, etc.
#          and mispelling will cause rollback to a default font or worse!!!
#
active_font: "JetBrainsMono Nerd Font"
nerd_fonts:
  - FiraCode
  - JetBrainsMono
  - Lilex
  - RobotoMono
antidote_plugins:
  - zsh-users/zsh-syntax-highlighting
  - zsh-users/zsh-autosuggestions
  - zsh-users/zsh-completions
  - zsh-users/zsh-history-substring-search
  - MichaelAquilina/zsh-you-should-use
  - Aloxaf/fzf-tab
#
# List of hosts to ssh from iTerm2
#
ssh_hosts:
  - name: M1-Nando
    address: m1-nando.local
  - name: M4-Nando
    address: m4-nando.local
  - name: Ubu-Laptop
    address: ubu-laptop.local
