- name: Install oh-my-posh on Ubuntu
  ansible.builtin.shell:
    cmd: curl -s https://ohmyposh.dev/install.sh | bash -s
  when: ansible_distribution == "Ubuntu"

- name: Install oh-my-posh on MacOS
  community.general.homebrew:
    name: oh-my-posh
    state: present
  when: ansible_distribution == "MacOSX"

- name: Copy the oh-my-posh directory
  ansible.builtin.copy:
    src: ../files/home/config/oh-my-posh/
    dest: "{{ ansible_env.HOME }}/.config/oh-my-posh/"
    mode: 0755
# - name: Create directory for oh-my-posh configuration
#   ansible.builtin.file:
#     path: "{{ ansible_env.HOME }}/.config/oh-my-posh"
#     state: directory
#     mode: 0755

# - name: Deploy oh-my-posh configuration file
#   ansible.builtin.copy:
#     src: ../files/oh-my-posh.toml
#     dest: "{{ ansible_env.HOME }}/.config/oh-my-posh/config.toml"
#     mode: 0644
