- name: Install core tools for Ubuntu
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - curl
      - fastfetch
      - fzf
      - gum
      - just
      - luarocks
      - nodejs
      - ripgrep
      - wget
  when: ansible_facts.distribution == "Ubuntu"

- name: Install core tools for MacOS
  community.general.homebrew:
    state: present
    name:
      - curl
      - fastfetch
      - fzf
      - gnu-tar
      - gum
      - just
      - luarocks
      - nodejs
      - ripgrep
      - wget
  when: ansible_facts.distribution == "MacOSX"
