- name: Install c/cpp tools for Ubuntu
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - clang
      - clang-tools
      - clang-format
  when: ansible_facts.distribution == "Ubuntu"
- name: Install c/cpp tools for MacOS
  community.general.homebrew:
    state: present
    name:
      - clang-format
  when: ansible_facts.distribution == "MacOSX"
- name: Install VS Code extensions for C/C++
  ansible.builtin.command: "code --force --install-extension {{ item }}"
  loop:
    - llvm-vs-code-extensions.vscode-clangd
    - xaver.clang-format
- name: Copy the clang-format config file to user's home folder
  ansible.builtin.copy:
    src: "{{ playbook_dir}}/files/home/clang-format"
    dest: "{{ ansible_facts.user_dir }}/.clang-format"
