#
# Allow passwordless sudo
#
- name: Allow passwordless sudo for {{ ansible_facts.user_id }}
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ ansible_facts.user_id }}
    create: yes
    line: "{{ ansible_facts.user_id }} ALL=(ALL) NOPASSWD: ALL"
#
# Install core tools
#
- name: Install core tools
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/core_tools.yml"
#
# Install EZA
#
- name: Install eza
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/eza.yml"
#
# Install develop tools
#
- name: Install develop tools
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/develop_tools.yml"
#
# Install zsh and make it the default shell
# Add extensions using antidote plugin manager
#
- name: Install zsh and make it the default shell
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/zsh.yml"
#
# Add a PROJECTS folder
#
- name: Install a Projects folder
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/projects_dir.yml"
#
# Configure github
#
- name: Install & configure github
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/github.yml"
#
# Install bat (a cat substitute with steroids)
# Note: needs zsh installed
#
- name: Install and configure bat
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/bat.yml"
#
# Install nerd fonts
#
- name: Install fonts
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/fonts.yml"
#
# Add the user's local bin folder
#
- name: Create user's .local/bin directory and ensure it's in PATH
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/local_bin.yml"
#
# Install a kool prompt
#
- name: Install oh-my-posh
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/oh-my-posh.yml"
#
# Install editors (Neovim & VS Code)
#
- name: Install VS Code
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/vscode.yml"
#
# Install Neovim
#
- name: Install neovim
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/neovim.yml"
#
# Install programming languages (Golang, Rust, Zig)
# Note: VS Code should be installed to add extensions
#
- name: Install cpp
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/cpp.yml"
  when: install_cpp == true
- name: Install golang
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/golang.yml"
  when: install_go == true
- name: Install rust
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/rust.yml"
  when: install_rust == true
- name: Install zig
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/zig.yml"
  when: install_zig == true
- name: Install c3
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/c3.yml"
  when: install_c3 == true
#
# Install a kool app to display os info in the terminal.
# Leave this as the last task!
#
- name: Install and configure fastfetch
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/tasks/fastfetch.yml"
