---
- hosts: localhost
  connection: local
  vars_files:
    - file: "{{ playbook_dir }}/vars/main.yml"

  tasks:
    - name: Debug task
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/debug.yml"
